#!/usr/bin/env python3
"""Render pass-by-pass ratios from retained outputs, without benchmark execution."""
import json,statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parent;DATA=ROOT.parent/'reports/data/kv-native-2026-10-08';REPORT=ROOT.parent/'reports/kv-native-2026-10-08.md'
def main():
 rows=[json.loads(x)for x in(DATA/'runs.jsonl').read_text().splitlines()];alloc=[json.loads(x)for x in(DATA/'allocations.jsonl').read_text().splitlines()];env=json.loads((DATA/'environment.json').read_text());storage=json.loads((DATA/'storage.json').read_text());checks=json.loads((DATA/'correctness.json').read_text())
 def get(mode,case,binary):return sorted([r for r in rows if r['mode']==mode and r['case']==case and r['binary']==binary],key=lambda r:r['pass'])
 def ratios(mode,case):return [g['ns_op']/r['ns_op']for g,r in zip(get(mode,case,'go-kv'),get(mode,case,'rust-kv'))]
 def ratio(mode,case):return statistics.median(ratios(mode,case))
 def table(mode):
  cases=list(dict.fromkeys(r['case']for r in rows if r['mode']==mode and r['binary']=='go-kv'));s=['| Case | Operations/pass | Median Go/native elapsed ratio | Passes 0–5 |','|---|---:|---:|---|']
  for c in cases:s.append(f"| `{c}` | {get(mode,c,'go-kv')[0]['iterations']:,} | {ratio(mode,c):.2f}× | "+'; '.join(f'{r:.2f}'for r in ratios(mode,c))+' |')
  return '\n'.join(s)
 def allocation_table():
  s=['| Case | Go heap allocations/op; bytes/op | Rust allocations/op; bytes/op |','|---|---:|---:|']
  for mode,case in [('kernel','key_loop'),('kernel','key_search'),('kernel','value_codec'),('kernel','json_codec'),('kernel','scan_materialize'),('bench','get_bytes'),('bench','get_raw'),('bench','get_json'),('bench','scan100'),('bench','set_bytes'),('bench','set_spill'),('bench','counter_add')]:
   pair=[]
   for binary in ['go-kv','rust-kv-telemetry']:
    r=next(r for r in alloc if r['mode']==mode and r['case']==case and r['binary']==binary);pair.append(f"{r['alloc_calls']/r['iterations']:.2f}; {r['alloc_bytes']/r['iterations']:.0f}")
   s.append(f"| `{mode}/{case}` | {pair[0]} | {pair[1]} |")
  return '\n'.join(s)
 safe=get('bench','sql_get','rust-kv');ffi=get('bench','sql_ffi_get','rust-kv');wrapper=[a['ns_op']/b['ns_op']for a,b in zip(safe,ffi)];go_rss=[r['process']['maxrss_kib']/1024 for r in rows if r['binary']=='go-kv'and r['mode']=='bench'];rs_rss=[r['process']['maxrss_kib']/1024 for r in rows if r['binary']=='rust-kv'and r['mode']=='bench'];rss_ranges=f"Go {min(go_rss):.1f}–{max(go_rss):.1f} MiB; native {min(rs_rss):.1f}–{max(rs_rss):.1f} MiB"
 go_key=statistics.median([a['ns_op']/b['ns_op']for a,b in zip(get('kernel','key_loop','go-kv'),get('kernel','key_search','go-kv'))]);rust_key=statistics.median([a['ns_op']/b['ns_op']for a,b in zip(get('kernel','key_loop','rust-kv'),get('kernel','key_search','rust-kv'))]);sourceid=env['rust-kv_sqlite']['sqlite_source_id()']
 p=['# KV algorithms and a native SQLite slice — 8 October 2026','',
 '**Exploratory uncommitted collection.** The user explicitly waived the harness-before-measurement commit gate. Exact source, lockfile, fixture, native archive and binary hashes are retained; this does not supply the review history of a committed harness. No production TinyStore code was changed.','',
 '| Question | Answer in this round | What follows |','|---|---|---|',
 f"| Does a synchronous native KV slice materially change equivalent paths? | 256-byte typed Get {ratio('bench','get_bytes'):.2f}×; typed JSON Get {ratio('bench','get_json'):.2f}×; 100-entry scan {ratio('bench','scan100'):.2f}×, using median paired Go/native loop elapsed ratios. | Continue native KV port work behind complete contract tests. |",
 f"| Are writes merely SQL-only comparisons? | Durable public Go/native Set {ratio('bench','set_bytes'):.2f}×; 4 KiB spilled overwrite {ratio('bench','set_spill'):.2f}×; durable counter Add {ratio('bench','counter_add'):.2f}×. | These single-caller loops do not predict grouped concurrent throughput. |",
 f"| Can a source-level algorithm alternative matter independently? | Bulk-copy key escaping changes Go loop/search elapsed by {go_key:.2f}× and Rust by {rust_key:.2f}× on the same fixed key set. | Treat each measured implementation separately; no universal language multiplier follows. |",
 f"| How much is the safe native wrapper? | Safe rusqlite/C-API SQL-only elapsed ratio {statistics.median(wrapper):.2f}× for one owning point-read control. | Do not attribute that cost to Rust itself or subtract it from every engine path. |",
 '| Do files and guards agree? | Matched schema, 56-command transcript and physical row snapshots, plus value-shape cross-reading, page/size bounds, failed-Take and overflow guards pass. | This is a working slice, not a complete production engine. |','',
 '## Environment and reproduction','',
 'The Go baseline is the real public API from `tinystore/source` at `e307c48a40126aad0e2873b6bf3aaedef8115483`, the production main baseline used by the metrics round. It is not the primary TinyStore checkout on its later local feature branch. Go 1.27.1, Rust 1.99.0, stock rusqlite 0.40.1 and external SQLite 3.53.4 are pinned. The locked Rust graph retains fetched crate checksums.','',
 f"SQLite source ID: `{sourceid}`. Full Go/native source IDs and compile-option inventories are in [environment.json](data/kv-native-2026-10-08/environment.json). The official amalgamation ZIP SHA-256 is `1e71ddf93849c6a6ecf58b827c0692073d2dd7ee40196158068f7b29f422e87d`; external static archive SHA-256 is `{env['native_archive_sha256']}`. Native THREADSAFE=1, automatic initialization and Unix VFS are intentional differences from the Wasm backend. The unchanged KV schema uses 4096-byte pages, WAL/FULL, fullfsync/checkpoint_fullfsync=1, foreign_keys=1, busy_timeout=5000, reader cache −1024 KiB and writer cache −4096 KiB. Native PRAGMAs are read back and retained. A byte-for-byte SQLite configuration match is not claimed.", '',
 'This is Docker Desktop on Windows/WSL2, with stores/build targets on a Linux Docker volume, CPU affinity 2, GOMAXPROCS=1 and GOGC=100. The shared host was kept quiet by explicit parent/agent RUN handshakes; no builds, tests or other engine measurements ran during collection. These are paired local loop elapsed ratios, not bare-Linux operation latencies, production rates or concurrent-throughput promises.','',
 'Machine inventory (the full uname/lscpu output is retained):','', '```text',env['machine'].strip(),'```','',
 f"Collection UTC: `{env['started_utc']}` to `{env['finished_utc']}`. Quiet-window calibration selects equal fixed Go/native counts targeting at least 100 ms for the faster candidate, then six balanced passes alternate Go→Rust and Rust→Go for every matched case. Calibration rows are retained separately and excluded from ratios. Each process opens a fresh copy of the identical Go-created fixture, warms 64 operations except one-shot Clear/Maintain, and returns one owning result at a time. Loop timers exclude opening, fixture generation, warmup and telemetry snapshots. GNU time CPU/fault/context-switch/peak-RSS counters cover the whole process including startup, setup and close; especially for one-shot Clear/Maintain they are not CPU/op measurements.", '',
 '```sh','cd <repo>/tinystore/kv-native-bench','python3 build.py','python3 check.py','python3 guard_proof.py','# In the quiet Linux container, with KV_WORK on a Linux volume:','GOMAXPROCS=1 GOGC=100 taskset -c 2 python3 run.py','python3 report.py','```','',
 'The [prototype README](../kv-native-bench/README.md) gives the toolchain/container setup. Source and binary hashes, fixture hash, command counts and UTC start/end of each process are retained in the raw files. All input data is deterministic; no private corpus is committed.','',
 '## Equivalent synchronous engine paths','',table('bench'),'',
 'A ratio above one means less native elapsed work for this identical operation trace. `get_bytes` uses typed bytes on both sides; `get_raw` compares an owned raw tagged value; `get_json` decodes the same document into owned fields. The native path black-boxes complete owning values/pages/documents before consuming them, and statements never lend bytes past reset. `getentry` consumes version text as well. `take_cycle` and `delete_cycle` include recreation, so they are two durable mutations per iteration. `clear_small` removes 256 spilled cells; `clear_mark` hides 10,001 cells; `expire` deletes 1200 spilled expired cells. Those one-shot cases have six independent file copies, not six repetitions against an already emptied branch.','',
 'The native slice has one synchronous writer and reader; it omits Go lifecycle/admission/reservation and grouped-commit scheduling. It keeps the original SQL rules and WAL/FULL commit semantics for these calls. Therefore these ratios measure an implemented native/backend/runtime slice against the complete public Go paths, not a pure language comparison. Mutating benchmark cases also compare final physical row snapshots after each paired run; revisions, values, expiries, spill references and orphan counts agree.','',
 '## Algorithm kernels','',table('kernel'),'',
 'The key corpus has 256 fixed valid UTF-8 keys, varied lengths and embedded zeroes; each path contains the same owners and escaping. `key_loop` appends byte by byte; `key_search` copies runs between zeroes. The Rust search uses its slice scan and Go its standard IndexByte implementation, so the alternative is measured as implemented, not a claim that their library internals are identical. `value_codec` is an owned 8-byte big-endian encode/decode primitive, not Go generic reflection dispatch. `json_codec` serializes the same borrowed fields and deserializes owned fields; complete decoded documents are materialized. `scan_materialize` owns 100 keys and 256-byte values. `ttl_guard` exercises independent observed/expected revisions, expiry edges and hidden-row flags; its checked truth table admits exactly two of eight cases. No SQL runs in these kernels.','',
 '## Wrapper, allocation and memory evidence','',
 f"The SQL-only `sql_get` row is a prepared `select value from cells where bucket=1 and path=?1`, with one copied owning 256-byte result. Its paired Go/native elapsed ratio is {ratio('bench','sql_get'):.2f}×. Native safe-rusqlite/raw-C-API ratios by pass are "+'; '.join(f'{x:.2f}'for x in wrapper)+f" (median {statistics.median(wrapper):.2f}×). The C-API control checks prepare/bind/step/reset/finalize return codes, bounds the result and copies it before reset. It is not the engine backend and supplies no evidence about other wrappers, writes or an optimized full engine.", '',allocation_table(),'',
 'Go counters are runtime heap allocation deltas captured outside the timer. Rust allocation counters come from a separate instrumented binary; its elapsed timings are diagnostic only and excluded from every ratio. Rust global allocation counts exclude SQLite C mallocs, while Go runtime accounting includes its own driver/Wasm allocations. SQLite cache/status plus RSS cover additional resident memory; these are different accounting domains, not directly comparable total allocated-byte budgets. Native reader/writer cache hits, misses, writes, spills, resident cache bytes, statement bytes and commit counts are retained per run. Go SQLite counters are available only for its separate internal/sqlite SQL-control connection, because the public KV handle exposes none.','',
 f"Whole-process peak RSS ranges across engine runs: {rss_ranges}. Current VmRSS/VmHWM snapshots before and after loops are retained separately. Peak RSS includes engine setup and caches, not just a returned value. It does not establish a production memory budget or the cost of concurrent readers.", '',
 '## Payload and physical file','',
 f"The fixture holds {storage['logical_payload_bytes']:,} logical value bytes in a {storage['file_bytes']:,}-byte closed SQLite file; fixture SHA-256 `{storage['fixture_sha256']}`. Both candidates start from this exact file. No space-saving format change is attempted. [storage.json](data/kv-native-2026-10-08/storage.json) partitions every page using TinyStore internal/dbstat, rather than treating encoded payload as file size.",'', '| Object | Pages | Bytes |','|---|---:|---:|']
 for obj in storage['objects']:p.append(f"| `{obj['Name']}` | {obj['Pages']:,} | {obj['Bytes']:,} |")
 p+=['', '## Correctness, limits and what follows','',
 f"Rust unit tests pass path escaping/bounds, owned numeric bit retention and alternate key-kernel equivalence. The cross-language oracle compares {checks['semantic_commands']} normalized API results and complete post-trace row snapshots. It covers empty/short/512/513/4096/1-MiB values, strings, signed/unsigned integer representations, -0 and float32/float64 signaling/quiet NaN payloads, JSON structs, deep/zero-containing owners, integer/text key identity, CAS conflicts, failed-Take rollback, expiry/DefaultTTL preservation and recreation, Touch version retention, small/marked Clear, maintenance and durable-counter overflow. Delete/expire/reopen preserve nonrepeating successful versions; an intentional rollback consumes a revision gap. 32 native-written numeric/raw shapes reopen through Go's typed API. Missing spill reads/takes report corruption and keep the cell. A four-MiB scan page stops after four one-MiB values, resumes for the fifth, and a value past one MiB is refused.", '',
 'The failed-Take mutant was built in a temporary copied crate, without changing the measured source; removing its decode check makes the oracle observe a successful bad Take and missing key. [guard-proof.json](data/kv-native-2026-10-08/guard-proof.json) retains broken/restored transcripts and mutant hashes. Raw semantic/corruption traces and length/hash-compacted page-bound outputs are retained beside it. Source tests ran in Linux; Windows/macOS production CI, full TinyStore task check/race/SDK suites and complete native engine race/crash tests were not run because production code was unchanged and this slice does not implement those runtime paths.','',
 'Native keys/owners are valid UTF-8 text only; production Go permits arbitrary key bytes. Arbitrary byte values remain exact. Native error text is not identical: normalized sentinel category and exact bucket/path identity are compared. The slice relies on a Go-created migrated schema and omits directory locks, bootstrap/migrations, lifecycle/gates, process memory reservation, concurrency/grouped commits, cancellation, full transactions/views, custom codecs/panics, background work, sliding expiry, relaxed counters, configs/watch, once, limiter/quota and a cache runtime. Its SetIfAbsent is a synchronous single-owner implementation, not a concurrency promise. Full contracts, crash tests and grouped concurrency remain gates before using it as TinyStore.','',
 'The evidence supports continuing a native KV port with the original schema and typed/raw vocabulary. The key-escaping alternative is a separate Go/Rust optimization candidate and needs representative production key distributions before adoption. The next step is runtime/concurrency equivalence and bare-Linux service measurements, not multiplying these local ratios into a production throughput claim.','',
 'Raw files: [runs](data/kv-native-2026-10-08/runs.jsonl), [allocations](data/kv-native-2026-10-08/allocations.jsonl), [environment and hashes](data/kv-native-2026-10-08/environment.json), [correctness](data/kv-native-2026-10-08/correctness.json), [Go transcript](data/kv-native-2026-10-08/trace-go.jsonl), [Rust transcript](data/kv-native-2026-10-08/trace-rust.jsonl).']
 REPORT.write_text('\n'.join(p)+'\n');print(REPORT)
if __name__=='__main__':main()
