#!/usr/bin/env python3
"""Render the local report from saved measurements without rerunning them."""
import json
from pathlib import Path
import statistics

ROOT = Path(__file__).resolve().parent
DATA = ROOT.parent / "reports/data/rust-kernels-2026-10-07"


def table(headers, rows):
    matrix = [headers, *[[str(v) for v in row] for row in rows]]
    widths = [max(len(row[i]) for row in matrix) for i in range(len(headers))]
    line = lambda row: "| " + " | ".join(v.ljust(w) for v, w in zip(row, widths)) + " |"
    return "\n".join([line(matrix[0]), line(["-" * w for w in widths]), *[line(row) for row in matrix[1:]]])


def main():
    env = json.loads((DATA / "environment.json").read_text())
    summary = {r["case"]: r for r in json.loads((DATA / "summary.json").read_text())}
    memory = [json.loads(line) for line in (DATA / "memory.jsonl").read_text().splitlines()]
    allocations = [json.loads(line) for line in (DATA / "allocations.jsonl").read_text().splitlines()]
    names = ["ingest/ordered/4096", "ingest/shuffled/4096", "ingest/shuffled/4096/typed_sort", "metrics/change/many/encode", "metrics/change/many/decode", "metrics/change/decimal/decode", "metrics/change/raw/encode", "metrics/packed/17/baseline/decode", "metrics/packed/17/chunked/decode", "records/width_17/decode", "records/width_17/decode_word"]
    timing_rows = [[name, f"{summary[name]['go_ns']/1000:.3f}", f"{summary[name]['rust_ns']/1000:.3f}", f"{summary[name]['speedup_go_over_rust']:.2f}×"] for name in names]
    pass_rows = [[name, "; ".join(f"{v/1000:.2f}" for v in summary[name]["passes_ns"]["go"]), "; ".join(f"{v/1000:.2f}" for v in summary[name]["passes_ns"]["rust"])] for name in names]
    memory_rows = []
    for name in dict.fromkeys(r["case"] for r in memory):
        for lang in ["go", "rust"]:
            selected = [r for r in memory if r["case"] == name and r["language"] == lang]
            median = lambda key: statistics.median(r[key] for r in selected)
            memory_rows.append([name, lang, f"{median('rss_kib')/1024:.2f}", f"{median('baseline_rss_kib')/1024:.2f}", f"{median('peak_rss_kib')/1024:.2f}", f"{median('capacity_output_bytes')/1048576:.2f}", f"{median('retained_harness_metadata_bytes')/1048576:.2f}"])
    allocation_names = ["metrics/change/many/decode", "records/width_17/decode", "ingest/ordered/4096", "ingest/shuffled/4096"]
    allocation_rows = [[r["case"], r["language"], f"{r['bytes_per_op']:.0f}", f"{r['allocs_per_op']:.0f}", r["output_capacity_bytes"]] for r in allocations if r["case"] in allocation_names]
    content = f"""# Rust kernels and SQLite feasibility — 2026-10-07

Preliminary local experiment. TinyStore source is unchanged at
`{env['tinystore_commit']}`. The prototype is uncommitted and unpublished;
content hashes pin the measured files in
[environment.json](data/rust-kernels-2026-10-07/environment.json). This does
not yet satisfy research's committed-harness requirement for an official round.

{table(['Question', 'Answer', 'What follows'], [
['Does Rust speed up the selected algorithms?', 'Yes for preparation and value changes; not every literal packing port.', 'Measure hot-path fractions before inferring whole-engine speed.'],
['Can Go improve without a rewrite?', 'Word packing improves the selected Go decoder by 8.89×.', 'Evaluate this algorithm in the production codec separately.'],
['Is retained memory lower?', 'Yes here, especially growing arrays; decoded data sizes remain equal.', 'Separate allocation churn, retained capacity and process RSS.'],
['Was SQLite migrated or benchmarked?', 'No. A separate bundled-rusqlite configuration/linking smoke passed.', 'Match SQLite version and port transaction semantics before a system benchmark.']])}

## Environment and reproduction

- Managed Linux container on an AMD EPYC 9V74 VM; three visible virtual CPUs,
  cgroup CPU quota `{env['cpu_quota']}`, 8 GiB memory limit. One process at a
  time, pinned to CPU {env['cpu_affinity']}; Go `GOMAXPROCS=1`, default GOGC=100.
- `{env['go']}`; `{env['rustc']}`; ordinary `cargo build --release`,
  without LTO overrides or native-CPU flags. Go uses `CGO_ENABLED=0`.
- Five Go/Rust pairs: G,R; R,G; G,R; R,G; G,R. Every reported calibration
  interval lasts at least 0.15 seconds. No builds or tests run during timings
  or RSS collection. This is a shared VM, not an isolated physical core.
- Collection started `{env['started_utc']}` and ended
  `{env['finished_utc']}` UTC. Timings and allocation counters finished first;
  memory collection resumed with locally installed GNU time after the initial
  driver found that tool missing. No measured source or binary changed.
- 54 deterministic fixtures, warm input reuse. Metrics: 240 samples;
  records: 1024 integers; ingestion: 240 or 4096 arrivals. Xorshift, SplitMix64
  and LCG fixtures are generated by the prototype source, without a corpus.
  Counts, input fingerprints and every output byte agree between Go/Rust.
- Twelve tests per language passed, along with original Go codec, metrics and
  records suites. Rust formatting, Go vet and Python syntax checks passed.
  No product changes were made; full repository CI, race tests, other OSes and
  SDK checks were not run for this standalone research prototype.

With the prototype in a research checkout, Linux Go/Rust/Python, `taskset`
and GNU time installed:

```sh
git -C tinystore/source checkout {env['tinystore_commit']}
cd tinystore/rust-spike
GOWORK=off CGO_ENABLED=0 python3 run.py --passes 5 --seconds 0.15
python3 render_report.py
```

The [prototype README](../rust-spike/README.md) describes ownership and scope.
Raw [timings](data/rust-kernels-2026-10-07/timings.jsonl),
[verification](data/rust-kernels-2026-10-07/verification.json),
[all 54 summaries](data/rust-kernels-2026-10-07/summary.json),
[allocation counters](data/rust-kernels-2026-10-07/allocations.jsonl) and
[RSS processes](data/rust-kernels-2026-10-07/memory.jsonl) are preserved.

## Speed

Medians in microseconds per owning-output operation. A ratio above 1 means
the Rust version is faster. These are selected algorithms, not Ingest/Read API
throughput. Samples' validation, labels, clocks, SQLite, locking, durability,
whole codec selection and records dictionary/FSE planning are excluded.

{table(['Case', 'Go µs/op', 'Rust µs/op', 'Go / Rust'], timing_rows)}

Ordered preparation is 3.03× faster, shuffled preparation 3.82×, and the
selected change-value decoder 4.50×. The map/sort comparison also changes
standard-library implementation: Rust HashMap and typed unstable sort versus
Go's map and sort.Slice. Go's typed-sort variant cuts shuffled preparation from
949.74 to 634.26 µs; Rust remains about 2.52× faster against that variant.

The literal 17-bit residual decoder has no demonstrated improvement: medians
are close and pass ranges overlap. A word-reservoir algorithm changes the Go
decoder from 4.064 to 0.457 µs, an 8.89× improvement. That optimized Go decoder
is about 9.33× faster than the literal Rust decoder; optimized Rust is another
2.06× faster than optimized Go. Both algorithms preserve the same packed bytes
and validation checks. This separates an algorithmic gain from choosing Rust.

Five passes, microseconds; the full data retains nanoseconds:

{table(['Case', 'Go passes µs', 'Rust passes µs'], pass_rows)}

There is visible shared-VM variance, especially some small cases. Close ratios
do not establish a regression or a stable gain. Input and output black boxes
prevent optimizer specialization in Rust; Go's global owning sink forces
escaping outputs. Rust destruction is immediate, Go reclamation amortized.

## Memory

Each fresh process retains approximately 64 MiB of identical logical output
after equal warmup. Go snapshots follow explicit GC. RSS includes executable
pages, stacks, retained allocator pages and harness overhead. These numbers
are post-construction observations, not steady-state engine memory limits.
All fixtures are constructed before filtering; unrelated closures are then
discarded. Baselines capture startup and fixture allocator effects.

Medians over three processes per language/case, all sizes in MiB:

{table(['Case', 'Lang', 'RSS', 'Baseline RSS', 'Peak RSS', 'Output capacity', 'Harness metadata'], memory_rows)}

Decoded buffers have equal capacities. Their RSS difference is modest:
69.54 versus 65.62 MiB for records and 74.52 versus 66.02 MiB for metric
changes. The harness itself retains larger Go metadata; this is reported
separately and is not a production-engine saving.

Preparation differs more: Go holds 80 MiB of array capacity for 64 MiB of
logical samples, versus Rust's 64 MiB. Growing slices and vectors follow
different policies. In the first Go shuffled-memory pass, live heap is 80.18
MiB while heap_sys is 155.78 MiB; post-GC RSS can still include available heap
pages. This supports separating live data from RSS. The experiment does not
isolate the effects of preallocation, GC tuning or allocator page release, so
it does not prove that an equivalent retained footprint is impossible in Go.

Allocation-only counters, outside timing runs:

{table(['Case', 'Lang', 'Allocated B/op', 'Allocations/op', 'Output capacity B'], allocation_rows)}

Go TotalAlloc counts rounded heap sizes; the separate Rust counting allocator
counts requested layouts and whole reallocation requests. These are allocation
churn metrics, not directly equivalent live-memory or RSS measurements. Records
Rice encoding uses fresh output here, while production reuses encoder scratch.

## SQLite feasibility

The [SQLite smoke](../sqlite-rust-spike/README.md) builds synchronous
`rusqlite = 0.40.1` with bundled SQLite, cache and limits features. SQLite is
linked into the executable: [ldd](../sqlite-rust-spike/evidence/ldd.txt) and
[ELF dependencies](../sqlite-rust-spike/evidence/readelf-dynamic.txt) show no
libsqlite3.so. Linux libc, libm, libgcc and the loader remain dynamic. A C
compiler is needed at build time; a fully static Linux artifact needs a
separate target/toolchain such as musl.

Both [4096-page](../sqlite-rust-spike/evidence/smoke-4096.txt) and
[1024-page](../sqlite-rust-spike/evidence/smoke-1024.txt) runs pass WAL,
foreign_keys, busy_timeout=5000, synchronous=FULL, fullfsync,
checkpoint_fullfsync, 1 MiB connection cache, 32 prepared programs,
query_only readers, BEGIN IMMEDIATE writer and deferred-reader snapshot
checks. They also check savepoint isolation, native SQLite value types,
SQLITE_LIMIT_LENGTH, disabled DQS/trusted_schema and no repreparation for
`LIMIT CAST(? AS INTEGER)`.

This proves configuration and linking feasibility, not a complete port.
Reader pools, grouped-write scheduling, cancellation/rollback, admission,
migrations, connection recovery and cross-platform VFS behavior remain.
Keep engine page sizes and cache differences, including KV's 4 MiB writer
cache; avoid changing FULL durability to manufacture a speedup.

Current TinyStore has SQLite 3.53.4 translated ahead of time from Wasm into
Go, with a Go VFS; there is no SQLite runtime Wasm interpreter in that stack.
The bundled smoke reports SQLite 3.53.2 with native Unix VFS. A future benchmark
must control the version and record build-option/VFS differences. Go's
THREADSAFE=0 applies to isolated translated instances and must not simply be
copied into a shared native C library. The smoke keeps THREADSAFE=1 and owns
each NO_MUTEX connection individually. Native SQLite malloc allocations bypass
Rust's allocator; use RSS plus SQLite memory/db-status counters for that round.

Rusqlite is the first candidate because its synchronous API maps directly to
this connection model. [SQLx](https://github.com/launchbadge/sqlx/blob/main/sqlx-sqlite/src/connection/mod.rs)
uses worker threads and channels for SQLite's async interface. Raw
libsqlite3-sys is rusqlite's underlying C binding, appropriate only for specific
API gaps. [Turso's compatibility document](https://github.com/tursodatabase/turso/blob/main/COMPAT.md)
currently lists gaps involving foreign_key_check, checkpoint_fullfsync and
WITHOUT ROWID mutation, which TinyStore uses. It is not a drop-in replacement
for these contracts.

## What follows

First evaluate the word-reservoir codec inside Go with production profiles.
Then compare one complete metrics or records path against a Rust/native-SQLite
candidate with the same schema, versions where possible, durability, cache
budgets, concurrency and errors. Match prepared-query behavior and preserve
transaction scheduling rather than checking pragmas alone.

The selected loops justify a further experiment; they do not justify a whole
rewrite yet. A 3× kernel improvement yields only 1.07× total speed if the kernel
accounts for 10% of execution, 1.20× at 25%, or 1.50× at 50%. The current public
API profile must establish that fraction. No total-engine speed or RAM saving
has been measured in this round.
"""
    (ROOT.parent / "reports/rust-kernels-2026-10-07.md").write_text(content)


if __name__ == "__main__": main()
