#!/usr/bin/env python3
"""Read retained measurements into medians/distributions and a dated report."""
import json,statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parent;DATA=ROOT.parent/'reports/data/kv-optimization-2026-10-09';REPORT=ROOT.parent/'reports/kv-optimization-2026-10-09.md'
def main():
 rows=[json.loads(x)for x in(DATA/'runs.jsonl').read_text().splitlines()];alloc=[json.loads(x)for x in(DATA/'allocations.jsonl').read_text().splitlines()];phases=[json.loads(x)for x in(DATA/'phases.jsonl').read_text().splitlines()];env=json.loads((DATA/'environment.json').read_text())
 def get(case,v):return sorted([r for r in rows if r['case']==case and r['variant']==v],key=lambda r:r['pass'])
 def median(case,v):return statistics.median(r['ns_op']for r in get(case,v))
 def ratio(case,a,b):return statistics.median(x['ns_op']/y['ns_op']for x,y in zip(get(case,a),get(case,b)))
 cases=list(dict.fromkeys(r['case']for r in rows));vs=['go','old','normalized','paths','transactions','optimized']
 summary={c:{v:{'elapsed_us_op_median':median(c,v)/1000,'elapsed_us_op_passes':[r['ns_op']/1000 for r in get(c,v)]}for v in vs+['go-extended']if get(c,v)}for c in cases};(DATA/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')
 p=['# KV normalization and optimization — 9 October 2026','','**Exploratory uncommitted collection.** The user explicitly waived the pre-measurement harness commit. Exact source/binary/lockfile/fixture hashes and six balanced same-session passes are retained. Original 8 October prototype files/results and production TinyStore remain unchanged.','',
 'The old native benchmark did extra return work: Set/CAS and Take/Delete recreation copied the key, deep-cloned the input value and materialized an owned Entry. Go Set invokes SetEntry internally, but its internal Entry reuses the caller key/value. The new no-result Set returns `Result<()>` after writing only metadata. Explicit SetEntry returns an input-borrowing result with checked key/value pointer identity. Reads and Take continue to materialize owned results.','',
 '| Variant | Behavior |','|---|---|','| Go | Original public API executable from production main e307c48 |','| old | Original stock-rusqlite native executable, with extra owned Entry return work |','| normalized | Explicit no-result Set/CAS/recreation and borrowed SetEntry, original path/transaction algorithms |','| paths | Normalized plus precomputed branch prefix and bulk key escaping |','| transactions | Normalized plus cached safe transaction/savepoint statements |','| optimized | Both additional changes |','',
 '## Same-session results','',
 'Cells are median measured synchronous loop elapsed **microseconds per operation**, not bare-Linux latency guarantees. Ratios use medians of paired per-pass ratios; a Go/native ratio above one favors native. Every case has fixed equal counts selected before the six balanced passes.','',
 '| Case | Count/pass | Go μs/op | Old native | Normalized | Paths | Transactions | Optimized | Go/optimized ratio |','|---|---:|---:|---:|---:|---:|---:|---:|---:|']
 for c in cases:
  usego='go'if get(c,'go')else'go-extended';cells=[f'{median(c,v)/1000:.3f}'if get(c,v)else'—'for v in vs[1:]];p.append(f"| `{c}` | {get(c,usego)[0]['iterations']:,} | {median(c,usego)/1000:.3f} | "+' | '.join(cells)+f" | {ratio(c,usego,'optimized'):.2f}× |")
 p+=['','Paired attribution:','', '| Case | Old/normalized | Normalized/paths | Normalized/transactions | Normalized/combined |','|---|---:|---:|---:|---:|']
 for c in ['set_bytes','set_spill','cas','take_cycle','delete_cycle','counter_add','get_bytes','scan100']:p.append(f"| `{c}` | {ratio(c,'old','normalized'):.3f}× | {ratio(c,'normalized','paths'):.3f}× | {ratio(c,'normalized','transactions'):.3f}× | {ratio(c,'normalized','optimized'):.3f}× |")
 p+=['','Full per-pass distributions (μs/op), in pass order 0–5:','', '| Case | Variant | Passes |','|---|---|---|']
 for c in cases:
  for v in vs+['go-extended']:
   if get(c,v):p.append(f"| `{c}` | {v} | "+'; '.join(f'{r["ns_op"]/1000:.3f}'for r in get(c,v))+' |')
 p+=['','## Write phase and allocation evidence','','Phase timers run only in the separate diagnostic binary; they split transaction begin/savepoint, the write body, release and FULL commit. Its timings are excluded from the performance table. The profile build splits release/commit commands even in normalized mode so the boundary can be observed.','', '| Case | Variant | Begin/savepoint μs/op | Body | Release | Commit | Commit share |','|---|---|---:|---:|---:|---:|---:|']
 for r in phases:
  n=r['iterations'];a=r['phase_ns'];p.append(f"| `{r['case']}` | {r['variant']} | "+' | '.join(f'{x/n/1000:.3f}'for x in a)+f" | {a[3]/sum(a):.1%} |")
 p+=['','Global allocator diagnostics (SQLite C allocations excluded for Rust), separately instrumented and never used for speed ratios:','', '| Case | Variant | Allocations/op | Allocated bytes/op |','|---|---|---:|---:|']
 for r in alloc:p.append(f"| `{r['case']}` | {r['variant']} | {r['alloc_calls']/r['iterations']:.2f} | {r['alloc_bytes']/r['iterations']:.1f} |")
 p+=['','[syscalls.jsonl](data/kv-optimization-2026-10-09/syscalls.jsonl) retains separate strace sync/read/write counts. Ptrace alters timing; those elapsed times are not performance evidence. GNU time CPU/fault/context-switch/RSS values cover entire processes including connection setup, warmup and close, not isolated loop CPU/op. Native reader/writer cache counters and commit counts are retained per run.','',
 '## Correctness and limitations','','All four tuning modes pass the 56-command normalized result/physical snapshot oracle and a second 56-command no-result API trace; 32 native-written typed/raw shapes reopen through Go. Guards retain exact float64/float32 NaN/-0 bits, uint64, empty/binary/string/JSON/spilled values, 1 MiB value/4 MiB page caps, failed-Take rollback, missing spills, stale CAS, counter overflow, DefaultTTL overwrite/recreate, Touch versions, marked Clear and reopen revisions. Borrowed SetEntry must reuse the original key/value addresses. Separate temporary mutants prove both bad-Take rollback and input-ownership regressions fail. Every timed mutating pair/triple/six-way group compares complete final committed rows, revisions, expiries, spill references and orphan counts.','',
 'All variants keep original KV schema and bounds, WAL/FULL durability and savepoints. Native Set has no allocation for a returned Entry; safe rusqlite still copies bound bytes according to its normal ownership rules. Prepared transaction statements are executed through safe rusqlite to DONE/reset; failed bodies roll back, and a commit failure attempts rollback and reports outcome unknown. This prototype still lacks concurrent grouped commits, directory lifecycle/locks, memory reservation/cancellation, migration bootstrap, full user transactions/views, background maintenance, sliding/relaxed counters, config/watch/once/quota/limiter and custom codecs/panics. UTF-8 text keys only; arbitrary-byte values remain exact. Those omissions prohibit treating these synchronous ratios as a finished native engine.','',
 'The new 64 KiB and explicit SetEntry modes compare new public Go runner/native variants only; the unchanged old executable has no such mode. Each starts from a fresh identical original fixture. Native allocation accounting excludes SQLite C mallocs; Go heap and native allocation bytes have different accounting domains. Payload/file/object sizes remain the original format, retained in storage.json; no compression or storage saving is claimed.','',
 '## Environment and reproduction','',f"Collection UTC `{env['started_utc']}` to `{env['finished_utc']}`. AMD Ryzen 7 7700, Docker Desktop WSL2, Linux volume stores/targets, taskset CPU 2, GOMAXPROCS=1, GOGC=100. Cgroup limits: `{env['cgroup']}`. Competing research builds/tests/measurements were paused by explicit coordination; desktop/background activity outside that coordination was uncontrolled. This is local Windows/WSL2 evidence, not bare-Linux latency or concurrent-throughput guidance.",'',
 'Production source: `e307c48a40126aad0e2873b6bf3aaedef8115483`; previous research audit commit `4e82af66b38ee057e29d3bbc7b25abd32320d95e`. Go1.27.1, Rust1.99.0, stock rusqlite0.40.1, external official SQLite3.53.4. Source IDs and complete compile options/PRAGMAs are retained. Original native THREADSAFE/mutex/VFS/automatic-initialization differences from Go/Wasm remain. Initial/final original and new source/binary hashes must agree before run.py succeeds.','',
 '```sh','cd <repo>/tinystore/kv-opt-bench','python3 build.py','KV_TUNING=0 python3 check.py','KV_TUNING=1 python3 check.py','KV_TUNING=2 python3 check.py','KV_TUNING=3 python3 check.py','python3 guard_proof.py','python3 ownership_proof.py','python3 build.py --metadata-only','# In the coordinated quiet Linux window:','GOMAXPROCS=1 GOGC=100 taskset -c 2 python3 run.py','python3 report.py','```','',
 '[README](../kv-opt-bench/README.md) documents setup and API/runtime limits. [environment](data/kv-optimization-2026-10-09/environment.json), [runs](data/kv-optimization-2026-10-09/runs.jsonl), [summary](data/kv-optimization-2026-10-09/summary.json), [calibration](data/kv-optimization-2026-10-09/calibration.jsonl), [phases](data/kv-optimization-2026-10-09/phases.jsonl), [allocations](data/kv-optimization-2026-10-09/allocations.jsonl), [ownership mutant](data/kv-optimization-2026-10-09/ownership-proof.json) and the original failed-Take mutant proof are retained. Linux builds/formatting, three unit tests, all four integration modes and mutation proofs ran. Full production CI/race/SDK suites and Windows/macOS execution were not run; production is unchanged and the native slice lacks their runtime paths.']
 REPORT.write_text('\n'.join(p)+'\n');print(REPORT)
if __name__=='__main__':main()
